=== jradbayrem/XML_TUTORIAL/03_XML_Schema/src/03_Schemadivise/encyclopedie1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<!-- les elements de type simple -->
	<xsd:element name="nom" type="xsd:string" />
	<xsd:element name="prenom" type="xsd:string" />
	<xsd:element name="publication" type="xsd:nonNegativeInteger" />

	<!-- les elements de type complexe -->
	<xsd:element name="image" type="imgeType" />
	<xsd:element name="personne" type="personnetype" />


	<!-- Defintinion des types simples -->
	<xsd:simpleType name="sexeType">
		<xsd:restriction base="xsd:string">
			<!-- maxExclusive, pattern, minInclusive, length, maxLength -->
			<xsd:enumeration value="H" />
			<xsd:enumeration value="F" />
		</xsd:restriction>
	</xsd:simpleType>

	<!-- Defintinion des types complexes -->
	<xsd:complexType name="imgeType">
		<xsd:attribute name="src" type="xsd:anyURI" use="required" />
	</xsd:complexType>


	<xsd:complexType name="personnetype">
		<xsd:all>
			<xsd:element ref="nom" />
			<xsd:element ref="prenom" />
			<xsd:element ref="publication" minOccurs="1" />
			<xsd:element ref="image" minOccurs="0" />
		</xsd:all>
		<xsd:attribute name="dn" type="xsd:date" />
		<xsd:attribute name="id" type="xsd:ID" use="required" />
		<xsd:attribute name="ville" type="xsd:string" fixed="Nantes"
			use="optional" />
		<xsd:attribute name="pere" type="xsd:IDREF" use="optional" />
		<xsd:attribute name="sexe" type="sexeType" />
	</xsd:complexType>

	<xsd:complexType name="ecyclopedieType">
		<xsd:sequence>
			<xsd:element ref="personne" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<!-- L'element racine -->
	<xsd:element name="ecyclopedie" type="ecyclopedieType" />



</xsd:schema>

=== jradbayrem/XML_TUTORIAL/03_XML_Schema/bin/03_Schemadivise/encyclopedie1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ecyclopedie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="encyclopedie1.xsd">
	<personne id="ddd" dn="2006-12-02" sexe="H" ville="Nantes">
		<nom>NOMANE</nom>
		<prenom>BOULMERDJ</prenom>
		<publication>0</publication>
		<image src="http://www.fsr.ac.ma/faculte.png" />
	</personne>

	<personne id="dd" dn="2006-12-02" sexe="H" pere="ddd">
		<prenom>TITI</prenom>
		<publication>1</publication>
		<nom>TOTO</nom>
	</personne>
</ecyclopedie>
