=== jradbayrem/XML_TUTORIAL/03_XML_Schema/bin/02_SchemaCompact/ecyclopedie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="encyclopedie">
		<complexType>
			<sequence>
				<element name="personne" minOccurs="0" maxOccurs="unbounded">
					<complexType>

						<!-- sequence définit une liste ordonnée -->
						<!-- choix choice; liste desordonée all -->
						<sequence>
							<element name="nom" type="string" />
							<element name="prenom" type="string" />
							<element name="publication" type="nonNegativeInteger" minOccurs="1" />

							<!-- élément vide avec attributs -->
							<element name="img" minOccurs="0">
								<complexType>
									<attribute name="src" type="anyURI" use="required" />
									<!-- optional, fixed, default -->
								</complexType>
							</element>
						</sequence>
						<attribute name="dn" type="date" />
						<attribute name="id" type="ID" use="required" />
						<attribute name="ville" type="string" fixed="Nantes" use="optional" />
							
						<attribute name="pere" type="IDREF" use="optional" />
						
						<attribute name="sexe">
							<simpleType>
								<restriction base="string">
								<!-- maxExclusive, pattern, minInclusive, length, maxLength -->
									<enumeration value="H"/>
									<enumeration value="F"/>
								</restriction>
							</simpleType>
						</attribute>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== jradbayrem/XML_TUTORIAL/03_XML_Schema/src/02_SchemaCompact/ecyclopedie.xml
<?xml version="1.0" encoding="UTF-8"?>
<encyclopedie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ecyclopedie.xsd">

	<personne id="ddd" dn="2006-12-02" sexe="H" ville="Nantes">
		<nom>NOMANE</nom>
		<prenom>BOULMERDJ</prenom>
		<publication>0</publication>
		<img src="http://www.fsr.ac.ma/faculte.png" />
	</personne>

	<personne id="dd" dn="2006-12-02" sexe="H" pere="ddd">
		<nom>TOTO</nom>
		<prenom>TITI</prenom>
		<publication>1</publication>
	</personne>

</encyclopedie>
