<?xml version="1.0" encoding="UTF-8"  standalone= "yes"?>
<!DOCTYPE encyclopedie [
<!ELEMENT encyclopedie     (personne*)>
<!ELEMENT personne  (nom,prenom,publication+,img?,emploi?)>
<!ELEMENT nom       (#PCDATA)>
<!ELEMENT prenom    (#PCDATA)>
<!ELEMENT publication (#PCDATA)>
<!ELEMENT img EMPTY>
<!ELEMENT emploi ANY>
<!ATTLIST personne sexe (H | F) #IMPLIED>
<!ATTLIST personne datenaissance CDATA #REQUIRED>
<!ATTLIST personne id ID #REQUIRED>
<!ATTLIST personne pere IDREF #IMPLIED>
<!ATTLIST personne ville CDATA #FIXED "Rabat">]>
<encyclopedie>
    <personne id="ddddd" datenaissance="1942-01-08" sexe="H">
        <nom>HAWKING</nom>
        <prenom>Stephen</prenom>
        <publication>Une brève histoire du temps</publication>
        <img/>
        <emploi><rue/><ville>Rabat</ville></emploi>
    </personne>
    <personne id="dddd" datenaissance="2222222" ville="Rabat">
        <nom>REEVES</nom>
        <prenom>Hubert</prenom>
        <publication>L'Univers expliqué à mes petits-enfants</publication>
        <publication>Patience dans l'azur, L'évolution cosmique</publication>
        <publication>Poussières d'étoiles</publication>
    </personne>
    <personne id="ddd" pere="dd" datenaissance="1879-03-14" sexe="H">
        <nom>EINSTEN</nom>
        <prenom>Albert</prenom>
        <publication>Des ondes gravitationnelles</publication>
        <publication>Sur la théorie quantique du rayonnement</publication>
    </personne>
    <personne id="dd" datenaissance="1867-11-07" sexe="F">
        <nom>CURIE</nom>
        <prenom>Marie</prenom>
        <publication>traité de radioactivité</publication>
    </personne>
</encyclopedie>